// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: enum_message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_UNSPECIFIED PaymentStatus = 0
	PaymentStatus_PAYMENT_PENDING            PaymentStatus = 1 // 已创建，待支付
	PaymentStatus_PAYMENT_SUCCESS            PaymentStatus = 2 // 支付成功
	PaymentStatus_PAYMENT_FAILED             PaymentStatus = 3 // 支付失败
	PaymentStatus_PAYMENT_CLOSED             PaymentStatus = 4 // 已关闭/超时
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PAYMENT_STATUS_UNSPECIFIED",
		1: "PAYMENT_PENDING",
		2: "PAYMENT_SUCCESS",
		3: "PAYMENT_FAILED",
		4: "PAYMENT_CLOSED",
	}
	PaymentStatus_value = map[string]int32{
		"PAYMENT_STATUS_UNSPECIFIED": 0,
		"PAYMENT_PENDING":            1,
		"PAYMENT_SUCCESS":            2,
		"PAYMENT_FAILED":             3,
		"PAYMENT_CLOSED":             4,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_message_proto_enumTypes[0].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_enum_message_proto_enumTypes[0]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_enum_message_proto_rawDescGZIP(), []int{0}
}

type PaymentMethod int32

const (
	PaymentMethod_PAYMENT_METHOD_UNSPECIFIED PaymentMethod = 0
	PaymentMethod_PAYMENT_METHOD_ALIPAY      PaymentMethod = 1
	PaymentMethod_PAYMENT_METHOD_WECHAT      PaymentMethod = 2
	PaymentMethod_PAYMENT_METHOD_BALANCE     PaymentMethod = 3 // 内部余额/模拟
)

// Enum value maps for PaymentMethod.
var (
	PaymentMethod_name = map[int32]string{
		0: "PAYMENT_METHOD_UNSPECIFIED",
		1: "PAYMENT_METHOD_ALIPAY",
		2: "PAYMENT_METHOD_WECHAT",
		3: "PAYMENT_METHOD_BALANCE",
	}
	PaymentMethod_value = map[string]int32{
		"PAYMENT_METHOD_UNSPECIFIED": 0,
		"PAYMENT_METHOD_ALIPAY":      1,
		"PAYMENT_METHOD_WECHAT":      2,
		"PAYMENT_METHOD_BALANCE":     3,
	}
)

func (x PaymentMethod) Enum() *PaymentMethod {
	p := new(PaymentMethod)
	*p = x
	return p
}

func (x PaymentMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_message_proto_enumTypes[1].Descriptor()
}

func (PaymentMethod) Type() protoreflect.EnumType {
	return &file_enum_message_proto_enumTypes[1]
}

func (x PaymentMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentMethod.Descriptor instead.
func (PaymentMethod) EnumDescriptor() ([]byte, []int) {
	return file_enum_message_proto_rawDescGZIP(), []int{1}
}

var File_enum_message_proto protoreflect.FileDescriptor

const file_enum_message_proto_rawDesc = "" +
	"\n" +
	"\x12enum_message.proto*\x81\x01\n" +
	"\rPaymentStatus\x12\x1e\n" +
	"\x1aPAYMENT_STATUS_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fPAYMENT_PENDING\x10\x01\x12\x13\n" +
	"\x0fPAYMENT_SUCCESS\x10\x02\x12\x12\n" +
	"\x0ePAYMENT_FAILED\x10\x03\x12\x12\n" +
	"\x0ePAYMENT_CLOSED\x10\x04*\x81\x01\n" +
	"\rPaymentMethod\x12\x1e\n" +
	"\x1aPAYMENT_METHOD_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PAYMENT_METHOD_ALIPAY\x10\x01\x12\x19\n" +
	"\x15PAYMENT_METHOD_WECHAT\x10\x02\x12\x1a\n" +
	"\x16PAYMENT_METHOD_BALANCE\x10\x03B\x12Z\x10./internal/pb;pbb\x06proto3"

var (
	file_enum_message_proto_rawDescOnce sync.Once
	file_enum_message_proto_rawDescData []byte
)

func file_enum_message_proto_rawDescGZIP() []byte {
	file_enum_message_proto_rawDescOnce.Do(func() {
		file_enum_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_enum_message_proto_rawDesc), len(file_enum_message_proto_rawDesc)))
	})
	return file_enum_message_proto_rawDescData
}

var file_enum_message_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_enum_message_proto_goTypes = []any{
	(PaymentStatus)(0), // 0: PaymentStatus
	(PaymentMethod)(0), // 1: PaymentMethod
}
var file_enum_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_enum_message_proto_init() }
func file_enum_message_proto_init() {
	if File_enum_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_enum_message_proto_rawDesc), len(file_enum_message_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enum_message_proto_goTypes,
		DependencyIndexes: file_enum_message_proto_depIdxs,
		EnumInfos:         file_enum_message_proto_enumTypes,
	}.Build()
	File_enum_message_proto = out.File
	file_enum_message_proto_goTypes = nil
	file_enum_message_proto_depIdxs = nil
}
