// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: pay_message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"` // 支付单号
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // 幂等ID（防重复支付）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayRequest) Reset() {
	*x = PayRequest{}
	mi := &file_pay_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayRequest) ProtoMessage() {}

func (x *PayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pay_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayRequest.ProtoReflect.Descriptor instead.
func (*PayRequest) Descriptor() ([]byte, []int) {
	return file_pay_message_proto_rawDescGZIP(), []int{0}
}

func (x *PayRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *PayRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type PayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        PaymentStatus          `protobuf:"varint,1,opt,name=status,proto3,enum=PaymentStatus" json:"status,omitempty"`                // 支付结果
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"` // 第三方交易号（可为空）
	PaidAt        int64                  `protobuf:"varint,3,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`                     // 支付完成时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayResponse) Reset() {
	*x = PayResponse{}
	mi := &file_pay_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayResponse) ProtoMessage() {}

func (x *PayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pay_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayResponse.ProtoReflect.Descriptor instead.
func (*PayResponse) Descriptor() ([]byte, []int) {
	return file_pay_message_proto_rawDescGZIP(), []int{1}
}

func (x *PayResponse) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *PayResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *PayResponse) GetPaidAt() int64 {
	if x != nil {
		return x.PaidAt
	}
	return 0
}

var File_pay_message_proto protoreflect.FileDescriptor

const file_pay_message_proto_rawDesc = "" +
	"\n" +
	"\x11pay_message.proto\x1a\x12enum_message.proto\"J\n" +
	"\n" +
	"PayRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\"u\n" +
	"\vPayResponse\x12&\n" +
	"\x06status\x18\x01 \x01(\x0e2\x0e.PaymentStatusR\x06status\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12\x17\n" +
	"\apaid_at\x18\x03 \x01(\x03R\x06paidAtB\x12Z\x10./internal/pb;pbb\x06proto3"

var (
	file_pay_message_proto_rawDescOnce sync.Once
	file_pay_message_proto_rawDescData []byte
)

func file_pay_message_proto_rawDescGZIP() []byte {
	file_pay_message_proto_rawDescOnce.Do(func() {
		file_pay_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pay_message_proto_rawDesc), len(file_pay_message_proto_rawDesc)))
	})
	return file_pay_message_proto_rawDescData
}

var file_pay_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pay_message_proto_goTypes = []any{
	(*PayRequest)(nil),  // 0: PayRequest
	(*PayResponse)(nil), // 1: PayResponse
	(PaymentStatus)(0),  // 2: PaymentStatus
}
var file_pay_message_proto_depIdxs = []int32{
	2, // 0: PayResponse.status:type_name -> PaymentStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pay_message_proto_init() }
func file_pay_message_proto_init() {
	if File_pay_message_proto != nil {
		return
	}
	file_enum_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pay_message_proto_rawDesc), len(file_pay_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pay_message_proto_goTypes,
		DependencyIndexes: file_pay_message_proto_depIdxs,
		MessageInfos:      file_pay_message_proto_msgTypes,
	}.Build()
	File_pay_message_proto = out.File
	file_pay_message_proto_goTypes = nil
	file_pay_message_proto_depIdxs = nil
}
