// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: payment_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_payment_service_proto protoreflect.FileDescriptor

const file_payment_service_proto_rawDesc = "" +
	"\n" +
	"\x15payment_service.proto\x1a\x11pay_message.proto\x1a\x15payment_message.proto\x1a\x13query_message.proto2\xaf\x01\n" +
	"\x0ePaymentService\x12>\n" +
	"\rCreatePayment\x12\x15.CreatePaymentRequest\x1a\x16.CreatePaymentResponse\x12 \n" +
	"\x03Pay\x12\v.PayRequest\x1a\f.PayResponse\x12;\n" +
	"\fQueryPayment\x12\x14.QueryPaymentRequest\x1a\x15.QueryPaymentResponseB\x12Z\x10./internal/pb;pbb\x06proto3"

var file_payment_service_proto_goTypes = []any{
	(*CreatePaymentRequest)(nil),  // 0: CreatePaymentRequest
	(*PayRequest)(nil),            // 1: PayRequest
	(*QueryPaymentRequest)(nil),   // 2: QueryPaymentRequest
	(*CreatePaymentResponse)(nil), // 3: CreatePaymentResponse
	(*PayResponse)(nil),           // 4: PayResponse
	(*QueryPaymentResponse)(nil),  // 5: QueryPaymentResponse
}
var file_payment_service_proto_depIdxs = []int32{
	0, // 0: PaymentService.CreatePayment:input_type -> CreatePaymentRequest
	1, // 1: PaymentService.Pay:input_type -> PayRequest
	2, // 2: PaymentService.QueryPayment:input_type -> QueryPaymentRequest
	3, // 3: PaymentService.CreatePayment:output_type -> CreatePaymentResponse
	4, // 4: PaymentService.Pay:output_type -> PayResponse
	5, // 5: PaymentService.QueryPayment:output_type -> QueryPaymentResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_payment_service_proto_init() }
func file_payment_service_proto_init() {
	if File_payment_service_proto != nil {
		return
	}
	file_pay_message_proto_init()
	file_payment_message_proto_init()
	file_query_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_service_proto_rawDesc), len(file_payment_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_service_proto_goTypes,
		DependencyIndexes: file_payment_service_proto_depIdxs,
	}.Build()
	File_payment_service_proto = out.File
	file_payment_service_proto_goTypes = nil
	file_payment_service_proto_depIdxs = nil
}
