// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: query_message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPaymentRequest) Reset() {
	*x = QueryPaymentRequest{}
	mi := &file_query_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPaymentRequest) ProtoMessage() {}

func (x *QueryPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_query_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPaymentRequest.ProtoReflect.Descriptor instead.
func (*QueryPaymentRequest) Descriptor() ([]byte, []int) {
	return file_query_message_proto_rawDescGZIP(), []int{0}
}

func (x *QueryPaymentRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

type QueryPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Method        PaymentMethod          `protobuf:"varint,6,opt,name=method,proto3,enum=PaymentMethod" json:"method,omitempty"`
	Status        PaymentStatus          `protobuf:"varint,7,opt,name=status,proto3,enum=PaymentStatus" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	PaidAt        int64                  `protobuf:"varint,9,opt,name=paid_at,json=paidAt,proto3" json:"paid_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPaymentResponse) Reset() {
	*x = QueryPaymentResponse{}
	mi := &file_query_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPaymentResponse) ProtoMessage() {}

func (x *QueryPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_query_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPaymentResponse.ProtoReflect.Descriptor instead.
func (*QueryPaymentResponse) Descriptor() ([]byte, []int) {
	return file_query_message_proto_rawDescGZIP(), []int{1}
}

func (x *QueryPaymentResponse) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *QueryPaymentResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *QueryPaymentResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *QueryPaymentResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *QueryPaymentResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *QueryPaymentResponse) GetMethod() PaymentMethod {
	if x != nil {
		return x.Method
	}
	return PaymentMethod_PAYMENT_METHOD_UNSPECIFIED
}

func (x *QueryPaymentResponse) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *QueryPaymentResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *QueryPaymentResponse) GetPaidAt() int64 {
	if x != nil {
		return x.PaidAt
	}
	return 0
}

var File_query_message_proto protoreflect.FileDescriptor

const file_query_message_proto_rawDesc = "" +
	"\n" +
	"\x13query_message.proto\x1a\x12enum_message.proto\"4\n" +
	"\x13QueryPaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\"\xa5\x02\n" +
	"\x14QueryPaymentResponse\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12&\n" +
	"\x06method\x18\x06 \x01(\x0e2\x0e.PaymentMethodR\x06method\x12&\n" +
	"\x06status\x18\a \x01(\x0e2\x0e.PaymentStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x17\n" +
	"\apaid_at\x18\t \x01(\x03R\x06paidAtB\x12Z\x10./internal/pb;pbb\x06proto3"

var (
	file_query_message_proto_rawDescOnce sync.Once
	file_query_message_proto_rawDescData []byte
)

func file_query_message_proto_rawDescGZIP() []byte {
	file_query_message_proto_rawDescOnce.Do(func() {
		file_query_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_query_message_proto_rawDesc), len(file_query_message_proto_rawDesc)))
	})
	return file_query_message_proto_rawDescData
}

var file_query_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_query_message_proto_goTypes = []any{
	(*QueryPaymentRequest)(nil),  // 0: QueryPaymentRequest
	(*QueryPaymentResponse)(nil), // 1: QueryPaymentResponse
	(PaymentMethod)(0),           // 2: PaymentMethod
	(PaymentStatus)(0),           // 3: PaymentStatus
}
var file_query_message_proto_depIdxs = []int32{
	2, // 0: QueryPaymentResponse.method:type_name -> PaymentMethod
	3, // 1: QueryPaymentResponse.status:type_name -> PaymentStatus
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_query_message_proto_init() }
func file_query_message_proto_init() {
	if File_query_message_proto != nil {
		return
	}
	file_enum_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_query_message_proto_rawDesc), len(file_query_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_query_message_proto_goTypes,
		DependencyIndexes: file_query_message_proto_depIdxs,
		MessageInfos:      file_query_message_proto_msgTypes,
	}.Build()
	File_query_message_proto = out.File
	file_query_message_proto_goTypes = nil
	file_query_message_proto_depIdxs = nil
}
